"""
AI-generated test suite for pawpal_system.py
Generated by: Claude (Anthropic) — PawPal+ CodePath Module 2
"""

import pytest
from datetime import date, datetime, timedelta
from pawpal_system import (
    Task, TaskType, Recurrence, TimeOfDay,
    Pet, Owner, TimeWindow, DailyPlan, ScheduledItem,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

def make_task(
    task_id="t_001",
    type=TaskType.WALK,
    duration=20,
    priority=3,
    pet_name="Buddy",
    preferred_time=TimeOfDay.ANYTIME,
    recurrence=Recurrence.DAILY,
):
    return Task(
        task_id=task_id,
        type=type,
        duration_minutes=duration,
        priority=priority,
        pet_name=pet_name,
        preferred_time=preferred_time,
        recurrence=recurrence,
    )


def make_owner(morning=60, evening=30, anytime=0):
    owner = Owner(owner_id="o1", name="Alex")
    if morning:
        owner.set_time_window(TimeOfDay.MORNING, morning)
    if evening:
        owner.set_time_window(TimeOfDay.EVENING, evening)
    if anytime:
        owner.set_time_window(TimeOfDay.ANYTIME, anytime)
    return owner


# ---------------------------------------------------------------------------
# Task — validation
# ---------------------------------------------------------------------------

class TestTaskValidation:
    def test_valid_task_creates_successfully(self):
        t = make_task(priority=3, duration=10)
        assert t.priority == 3
        assert t.duration_minutes == 10

    def test_priority_below_1_raises(self):
        with pytest.raises(ValueError, match="priority"):
            make_task(priority=0)

    def test_priority_above_5_raises(self):
        with pytest.raises(ValueError, match="priority"):
            make_task(priority=6)

    def test_zero_duration_raises(self):
        with pytest.raises(ValueError, match="duration"):
            make_task(duration=0)

    def test_negative_duration_raises(self):
        with pytest.raises(ValueError, match="duration"):
            make_task(duration=-5)

    def test_boundary_priority_1_ok(self):
        t = make_task(priority=1)
        assert t.priority == 1

    def test_boundary_priority_5_ok(self):
        t = make_task(priority=5)
        assert t.priority == 5


# ---------------------------------------------------------------------------
# Task — behaviour
# ---------------------------------------------------------------------------

class TestTaskBehaviour:
    def test_mark_complete(self):
        t = make_task()
        assert not t.is_completed
        t.mark_complete()
        assert t.is_completed

    def test_reschedule_sets_time(self):
        t = make_task()
        future = datetime(2030, 1, 1, 9, 0)
        t.reschedule(future)
        assert t.scheduled_time == future

    def test_is_overdue_past_time(self):
        t = make_task()
        t.scheduled_time = datetime(2000, 1, 1, 8, 0)
        assert t.is_overdue()

    def test_is_overdue_future_time(self):
        t = make_task()
        t.scheduled_time = datetime(2099, 1, 1, 8, 0)
        assert not t.is_overdue()

    def test_is_overdue_completed_task_never_overdue(self):
        t = make_task()
        t.scheduled_time = datetime(2000, 1, 1, 8, 0)
        t.mark_complete()
        assert not t.is_overdue()

    def test_is_overdue_no_scheduled_time(self):
        t = make_task()
        assert not t.is_overdue()

    def test_next_occurrence_daily(self):
        t = make_task(recurrence=Recurrence.DAILY)
        today = date(2026, 3, 15)
        assert t.next_occurrence(today) == date(2026, 3, 16)

    def test_next_occurrence_weekly(self):
        t = make_task(recurrence=Recurrence.WEEKLY)
        today = date(2026, 3, 15)
        assert t.next_occurrence(today) == date(2026, 3, 22)

    def test_next_occurrence_once_returns_none(self):
        t = make_task(recurrence=Recurrence.ONCE)
        assert t.next_occurrence(date.today()) is None

    def test_clone_for_date_is_incomplete(self):
        t = make_task()
        t.mark_complete()
        clone = t.clone_for_date(date(2026, 3, 16))
        assert not clone.is_completed

    def test_clone_for_date_has_new_id(self):
        t = make_task(task_id="t_001")
        clone = t.clone_for_date(date(2026, 3, 16))
        assert clone.task_id != "t_001"
        assert "2026-03-16" in clone.task_id

    def test_clone_preserves_type_and_priority(self):
        t = make_task(type=TaskType.MEDICATION, priority=5)
        clone = t.clone_for_date(date(2026, 3, 16))
        assert clone.type == TaskType.MEDICATION
        assert clone.priority == 5


# ---------------------------------------------------------------------------
# Pet
# ---------------------------------------------------------------------------

class TestPet:
    def setup_method(self):
        self.pet = Pet(pet_id="p1", name="Buddy", species="Dog", age=3)

    def test_add_task_sets_pet_name(self):
        t = make_task(pet_name="WRONG")
        self.pet.add_task(t)
        assert t.pet_name == "Buddy"

    def test_get_tasks_returns_all(self):
        self.pet.add_task(make_task("t1"))
        self.pet.add_task(make_task("t2"))
        assert len(self.pet.get_tasks()) == 2

    def test_remove_task(self):
        self.pet.add_task(make_task("t1"))
        self.pet.add_task(make_task("t2"))
        self.pet.remove_task("t1")
        ids = [t.task_id for t in self.pet.get_tasks()]
        assert "t1" not in ids
        assert "t2" in ids

    def test_get_pending_excludes_completed(self):
        t1 = make_task("t1")
        t2 = make_task("t2")
        t2.mark_complete()
        self.pet.add_task(t1)
        self.pet.add_task(t2)
        pending = self.pet.get_pending_tasks()
        assert len(pending) == 1
        assert pending[0].task_id == "t1"

    def test_tasks_for_time_of_day_includes_anytime(self):
        morning = make_task("t1", preferred_time=TimeOfDay.MORNING)
        anytime = make_task("t2", preferred_time=TimeOfDay.ANYTIME)
        self.pet.add_task(morning)
        self.pet.add_task(anytime)
        results = self.pet.tasks_for_time_of_day(TimeOfDay.MORNING)
        ids = {t.task_id for t in results}
        assert "t1" in ids
        assert "t2" in ids  # ANYTIME appears in every slot

    def test_tasks_for_time_of_day_excludes_other_slot(self):
        evening = make_task("t1", preferred_time=TimeOfDay.EVENING)
        self.pet.add_task(evening)
        results = self.pet.tasks_for_time_of_day(TimeOfDay.MORNING)
        assert not results

    def test_rollover_creates_clone_for_daily_task(self):
        t = make_task("t1", recurrence=Recurrence.DAILY)
        self.pet.add_task(t)
        tomorrow = date.today() + timedelta(days=1)
        new_tasks = self.pet.rollover_recurring_tasks(tomorrow)
        assert len(new_tasks) == 1
        assert not new_tasks[0].is_completed

    def test_rollover_skips_once_task(self):
        t = make_task("t1", recurrence=Recurrence.ONCE)
        self.pet.add_task(t)
        tomorrow = date.today() + timedelta(days=1)
        new_tasks = self.pet.rollover_recurring_tasks(tomorrow)
        assert len(new_tasks) == 0


# ---------------------------------------------------------------------------
# Owner
# ---------------------------------------------------------------------------

class TestOwner:
    def setup_method(self):
        self.owner = Owner(owner_id="o1", name="Alex")

    def test_add_pet(self):
        pet = Pet(pet_id="p1", name="Luna", species="Cat", age=2)
        self.owner.add_pet(pet)
        assert len(self.owner.pets) == 1

    def test_get_pet_by_name(self):
        pet = Pet(pet_id="p1", name="Luna", species="Cat", age=2)
        self.owner.add_pet(pet)
        assert self.owner.get_pet("Luna") is pet

    def test_get_pet_missing_returns_none(self):
        assert self.owner.get_pet("Ghost") is None

    def test_set_time_window_upserts(self):
        self.owner.set_time_window(TimeOfDay.MORNING, 30)
        self.owner.set_time_window(TimeOfDay.MORNING, 60)  # update
        assert self.owner.minutes_for_slot(TimeOfDay.MORNING) == 60
        assert len(self.owner.time_windows) == 1  # no duplicate entry

    def test_total_available_minutes(self):
        self.owner.set_time_window(TimeOfDay.MORNING, 30)
        self.owner.set_time_window(TimeOfDay.EVENING, 20)
        assert self.owner.total_available_minutes() == 50

    def test_minutes_for_missing_slot_is_zero(self):
        assert self.owner.minutes_for_slot(TimeOfDay.AFTERNOON) == 0

    def test_update_preference(self):
        self.owner.update_preference("note", "indoor only")
        assert self.owner.get_preferences()["note"] == "indoor only"

    def test_all_pending_tasks_across_pets(self):
        pet1 = Pet(pet_id="p1", name="Buddy", species="Dog", age=3)
        pet2 = Pet(pet_id="p2", name="Luna",  species="Cat", age=2)
        pet1.add_task(make_task("t1"))
        pet2.add_task(make_task("t2"))
        t_done = make_task("t3")
        t_done.mark_complete()
        pet1.add_task(t_done)
        self.owner.add_pet(pet1)
        self.owner.add_pet(pet2)
        pairs = self.owner.all_pending_tasks()
        ids = {t.task_id for t, _ in pairs}
        assert ids == {"t1", "t2"}   # completed t3 excluded

    def test_negative_time_window_raises(self):
        with pytest.raises(ValueError):
            TimeWindow(slot=TimeOfDay.MORNING, available_minutes=-1)


# ---------------------------------------------------------------------------
# DailyPlan — scheduler
# ---------------------------------------------------------------------------

class TestDailyPlanScheduler:
    def _plan_with(self, tasks_spec, morning=60, evening=30, anytime=0):
        """
        tasks_spec: list of (duration, priority, slot)
        Returns a generated DailyPlan.
        """
        owner = make_owner(morning=morning, evening=evening, anytime=anytime)
        pet = Pet(pet_id="p1", name="Buddy", species="Dog", age=3)
        owner.add_pet(pet)
        for i, (dur, pri, slot) in enumerate(tasks_spec):
            pet.add_task(make_task(
                task_id=f"t_{i}",
                duration=dur,
                priority=pri,
                preferred_time=slot,
            ))
        plan = DailyPlan(plan_id="plan1", date=date.today(), owner=owner)
        plan.generate()
        return plan

    def test_scheduled_duration_within_budget(self):
        plan = self._plan_with(
            [(30, 5, TimeOfDay.MORNING), (40, 4, TimeOfDay.MORNING)],
            morning=60,
        )
        assert plan.get_total_duration() <= 60

    def test_all_tasks_fit_when_budget_sufficient(self):
        plan = self._plan_with(
            [(10, 3, TimeOfDay.MORNING), (15, 4, TimeOfDay.MORNING)],
            morning=60,
        )
        assert len(plan.scheduled_items) == 2
        assert len(plan.skipped_items) == 0

    def test_task_skipped_when_over_budget(self):
        # 70-min task into a 60-min morning budget
        plan = self._plan_with(
            [(70, 5, TimeOfDay.MORNING)],
            morning=60,
        )
        assert len(plan.scheduled_items) == 0
        assert len(plan.skipped_items) == 1

    def test_knapsack_beats_greedy(self):
        """
        Budget = 30 min.
        Task A: priority=5, duration=31 (too long — greedy would block)
        Task B: priority=3, duration=30 (fits perfectly)
        Knapsack should schedule B, not skip everything.
        """
        plan = self._plan_with(
            [(31, 5, TimeOfDay.MORNING), (30, 3, TimeOfDay.MORNING)],
            morning=30,
        )
        assert plan.get_total_duration() == 30
        assert len(plan.scheduled_items) == 1

    def test_leftover_budget_fills_anytime(self):
        # Morning budget = 60, morning task = 20 → 40 min leftover → anytime task of 30 fits
        plan = self._plan_with(
            [(20, 3, TimeOfDay.MORNING), (30, 4, TimeOfDay.ANYTIME)],
            morning=60, evening=0, anytime=0,
        )
        ids = {i.task.task_id for i in plan.scheduled_items}
        assert "t_1" in ids  # anytime task scheduled via leftover

    def test_completion_rate_zero_initially(self):
        plan = self._plan_with([(10, 3, TimeOfDay.MORNING)], morning=60)
        assert plan.completion_rate() == 0.0

    def test_completion_rate_full(self):
        plan = self._plan_with([(10, 3, TimeOfDay.MORNING)], morning=60)
        plan.mark_task_complete("t_0")
        assert plan.completion_rate() == 1.0

    def test_completion_rate_partial(self):
        plan = self._plan_with(
            [(10, 3, TimeOfDay.MORNING), (10, 4, TimeOfDay.MORNING)],
            morning=60,
        )
        plan.mark_task_complete("t_0")
        assert plan.completion_rate() == pytest.approx(0.5)

    def test_mark_task_complete_returns_true_on_success(self):
        plan = self._plan_with([(10, 3, TimeOfDay.MORNING)], morning=60)
        assert plan.mark_task_complete("t_0") is True

    def test_mark_task_complete_returns_false_if_not_found(self):
        plan = self._plan_with([(10, 3, TimeOfDay.MORNING)], morning=60)
        assert plan.mark_task_complete("nonexistent") is False

    def test_remove_task(self):
        plan = self._plan_with([(10, 3, TimeOfDay.MORNING)], morning=60)
        removed = plan.remove_task("t_0")
        assert removed is True
        assert len(plan.scheduled_items) == 0

    def test_items_for_slot(self):
        plan = self._plan_with(
            [(10, 3, TimeOfDay.MORNING), (10, 3, TimeOfDay.EVENING)],
            morning=60, evening=30,
        )
        morning_items = plan.items_for_slot(TimeOfDay.MORNING)
        assert len(morning_items) == 1
        assert morning_items[0].slot == TimeOfDay.MORNING

    def test_explanation_contains_pet_name(self):
        plan = self._plan_with([(10, 3, TimeOfDay.MORNING)], morning=60)
        assert "Buddy" in plan.get_explanation()

    def test_empty_plan_completion_rate_is_zero(self):
        owner = make_owner(morning=0, evening=0, anytime=0)
        plan = DailyPlan(plan_id="p", date=date.today(), owner=owner)
        plan.generate()
        assert plan.completion_rate() == 0.0
